#!/usr/bin/env ruby

require 'erb'

module Compiler
  module_function

  def call
    thoughts_template = File.open("atbc.html.erb")
    erb_html = ERB.new(thoughts_template.read)
    @thoughts = [
    ]
    erb_html.result binding
  end
end

File.open('atbc.html', 'w') do |f|
  f.write Compiler.call
end
